# Generated by Django 5.0.2 on 2024-04-10 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='emp',
        ),
    ]
