# Generated by Django 5.0.2 on 2024-04-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0002_alter_emp_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='hiredate',
        ),
    ]
